### ISSUE TITLE
OAK-FFC-4P:  Character [-] at element [4] is not valid in Graph Resource Name 

### ISSUE THREAD

**Issue by ciniminis1** [luxonis/depthai-ros#396]
Hi @Serafadam ,
I try to lauch my OAK-FFC-4P in `rgbd` mode, but following error pops out after commit `b8d5779c2642ac5066f03eb2651057850de99974`:

`Character [-] at element [4] is not valid in Graph Resource Name [CAMB-2L_i_max_q_size].  Valid characters are a-z, A-Z, 0-9, / and _.`

`stereo` mode seems to be working fine. Could you please check it out? Thanks.

**Comment by Serafadam** [comment]
Hi, could you run `export DEPTHAI_DEBUG=1` and post logs?

**Comment by ciniminis1** [comment]
Sure, here you go:
```

roslaunch depthai_ros_driver camera.launch 
... logging to /home/pr_admin/.ros/log/cae1d2ce-4d83-11ee-bc82-53e0d77ead1b/roslaunch-OC0001-27617.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.50.149:46847/

SUMMARY
========

PARAMETERS
 * /oak/camera_i_base_frame: oak-d_frame
 * /oak/camera_i_cam_pitch: 0.0
 * /oak/camera_i_cam_pos_x: 0.0
 * /oak/camera_i_cam_pos_y: 0.0
 * /oak/camera_i_cam_pos_z: 0.0
 * /oak/camera_i_cam_roll: 0.0
 * /oak/camera_i_cam_yaw: 0.0
 * /oak/camera_i_enable_imu: True
 * /oak/camera_i_enable_ir: True
 * /oak/camera_i_floodlight_brightness: 0.0
 * /oak/camera_i_imu_from_descr: False
 * /oak/camera_i_ip: 
 * /oak/camera_i_laser_dot_brightness: 800.0
 * /oak/camera_i_mx_id: 
 * /oak/camera_i_nn_type: spatial
 * /oak/camera_i_parent_frame: oak-d-base-frame
 * /oak/camera_i_pipeline_type: rgbd
 * /oak/camera_i_publish_tf_from_calibration: False
 * /oak/camera_i_tf_imu_from_descr: true
 * /oak/camera_i_usb_port_id: 
 * /oak/camera_i_usb_speed: SUPER_PLUS
 * /oak/left_i_board_socket_id: 1
 * /oak/nn_i_nn_config_path: depthai_ros_drive...
 * /oak/right_i_board_socket_id: 2
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    oak (nodelet/nodelet)
    oak_nodelet_manager (nodelet/nodelet)
    oak_state_publisher (robot_state_publisher/robot_state_publisher)
    set_log_level (rosservice/rosservice)

ROS_MASTER_URI=http://192.168.50.149:11311

process[set_log_level-1]: started with pid [27656]
process[oak_state_publisher-2]: started with pid [27657]
process[oak_nodelet_manager-3]: started with pid [27658]
process[oak-4]: started with pid [27659]
[ INFO] [1694096919.196779944]: Loading nodelet /oak of type depthai_ros_driver/Camera to manager oak_nodelet_manager with the following remappings:
[ INFO] [1694096919.198573582]: waitForService: Service [/oak_nodelet_manager/load_nodelet] could not connect to host [192.168.50.149:45497], waiting...
[ INFO] [1694096919.209494276]: Initializing nodelet with 8 worker threads.
[ INFO] [1694096919.219261555]: waitForService: Service [/oak_nodelet_manager/load_nodelet] is now available.
[2023-09-07 16:28:39.330] [depthai] [info] DEPTHAI_DEBUG enabled, lowered DEPTHAI_LEVEL to 'debug'
[2023-09-07 16:28:39.330] [depthai] [debug] Library information - version: 2.22.0, commit:  from , build: 2023-06-20 18:09:51 +0000
[2023-09-07 16:28:39.331] [depthai] [debug] Initialize - finished
[ INFO] [1694096919.332396276]: No ip/mxid/usb_id specified, connecting to the next available device.
[2023-09-07 16:28:39.394] [depthai] [debug] Resources - Archive 'depthai-bootloader-fwp-0.0.26.tar.xz' open: 2ms, archive read: 61ms
[2023-09-07 16:28:39.662] [depthai] [debug] Resources - Archive 'depthai-device-fwp-f033fd9c7eb0b3578d12f90302e87759c78cfb36.tar.xz' open: 1ms, archive read: 330ms
[2023-09-07 16:28:39.854] [depthai] [debug] Searching for booted device: DeviceInfo(name=3.1.4, mxid=14442C10013FE7D600, X_LINK_BOOTLOADER, X_LINK_USB_VSC, X_LINK_MYRIAD_X, X_LINK_SUCCESS), name used as hint only
[2023-09-07 16:28:39.859] [depthai] [debug] Connected bootloader version 0.0.22
[2023-09-07 16:28:39.859] [depthai] [info] New bootloader version available. Device has: 0.0.22, available: 0.0.26
[set_log_level-1] process has finished cleanly
log file: /home/pr_admin/.ros/log/cae1d2ce-4d83-11ee-bc82-53e0d77ead1b/set_log_level-1*.log
[2023-09-07 16:28:40.793] [depthai] [debug] DeviceBootloader about to be closed...
[2023-09-07 16:28:40.794] [depthai] [debug] XLinkResetRemote of linkId: (0)
[2023-09-07 16:28:42.042] [depthai] [debug] DeviceBootloader closed, 1249
[2023-09-07 16:28:42.046] [depthai] [debug] Searching for booted device: DeviceInfo(name=3.1.4, mxid=14442C10013FE7D600, X_LINK_BOOTED, X_LINK_USB_VSC, X_LINK_MYRIAD_X, X_LINK_SUCCESS), name used as hint only
[14442C10013FE7D600] [3.1.4] [1.992] [system] [warning] PRINT:LeonCss: GPIO boot mode 0x3, interface SPI_MASTER_EFF
Setting aons(0..4) back to boot from flash (offset = 0)
====ENABLE WATCHDOG====1
initial keepalive, countdown: 10
PLL0: 700000 AUX_IO0: 24000 AUX_IO1: 24000 MCFG: 24000 MECFG: 24000
Board init ret 3
DepthAI Firmware - version: f033fd9c7eb0b3578d12f90302e87759c78cfb36
eeprom configuration version: 55AA0007
Reading VERSION 7 --- ->
eeprom configuration load from user area, status: 0
Reading VERSION 7 --- ->
Found a device/board entry matching the eeprom data - Board: OAK-FFC-4P (R7M1E7) Device: OAK-FFC-4P
Board options: 00000000
--> brdInit ...
brdInitAuxDevices: Error: SC = 27: io_initialize expander_cam_gpios_1 [OK]

spi_N25Q_init: Flash JEDEC ID: 20 bb 19
inited hal ---
def: 53 46 45 34 10 06 08 34 10 53 14 45 46 08 06
val: 53 46 45 34 10 06 08 34 10 53 14 45 46 08 06
Opening bus for IR driver: 0
Failed to probe IR driver LM3644
Opening bus for IR driver: 1
Failed to probe IR driver LM3644
Opening bus for IR driver: 2
Failed to probe IR driver LM3644
Opening bus for IR driver: 3
Failed to probe IR driver LM3644
Closing EEPROm!
MyriaX board configuration
pll0 frequency: 700000, ref0 frequency: 24000
Is booted from flash by bootloader: 0
Networking not available...
=== Enumerating on socket: Cam_A / RGB / Center
  >> Registered camera A12N02A (imx378) as /dev/Camera_0
camera socket: 0, name: CAMA-4L
        config - w: 1920, h: 1080, type: COLOR
        config - w: 3840, h: 2160, type: COLOR
        config - w: 4056, h: 3040, type: COLOR
Adding socket 0: cam 2. Sen name: IMX378
=== Enumerating on socket: Cam_B / Left
  >> Registered camera TG161B (ov9282) as /dev/Camera_1
camera socket: 1, name: CAMB-2L
        config - w: 1280, h: 720, type: MONO
        config - w: 1280, h: 720, type: COLOR
        config - w: 1280, h: 800, type: MONO
        config - w: 1280, h: 800, type: COLOR
Adding socket 1: cam 5. Sen name: OV9282
=== Enumerating on socket: Cam_C / Right
  >> Registered camera TG161B (ov9282) as /dev/Camera_2
camera socket: 2, name: CAMC-2L
        config - w: 1280, h: 720, type: MONO
        config - w: 1280, h: 720, type: COLOR
        config - w: 1280, h: 800, type: MONO
        config - w: 1280, h: 800, type: COLOR
Adding socket 2: cam 5. Sen name: OV9282
=== Enumerating on socket: CAM_D
initial keepalive, countdown: 9
initial keepalive, countdown: 8
Found a device/board entry matching the eeprom data - Board: OAK-FFC-4P (R7M1E7) Device: OAK-FFC-4P
Initializing XLink...
UsbPumpVscAppI_Event: 5 VSC2_EVENT_ATTACH
UsbPumpVscAppI_Event: 4 VSC2_EVENT_RESET
UsbPumpVscAppI_Event: 4 VSC2_EVENT_RESET
UsbPumpVscAppI_Event: 0 VSC2_EVENT_INTERFACE_UP
Done!
Usb connection speed: Super - USB 3.0
Temperature: Driver registered.
Temperature: Initialized driver.
Temperature: Sensor opened: CSS.
Temperature: Sensor opened: MSS.
Temperature: Sensor opened: UPA.
Temperature: Sensor opened: DSS.
[ INFO] [1694096923.113396458]: Camera with MXID: 14442C10013FE7D600 and Name: 3.1.4 connected!
[ INFO] [1694096923.114124362]: USB SPEED: SUPER
[14442C10013FE7D600] [3.1.4] [1.996] [system] [info] Memory Usage - DDR: 0.12 / 337.18 MiB, CMX: 2.04 / 2.50 MiB, LeonOS Heap: 7.51 / 80.03 MiB, LeonRT Heap: 2.89 / 41.06 MiB
[14442C10013FE7D600] [3.1.4] [1.996] [system] [info] Temperatures - Average: 42.24C, CSS: 43.04C, MSS 41.89C, UPA: 42.12C, DSS: 41.89C
[14442C10013FE7D600] [3.1.4] [1.996] [system] [info] Cpu Usage - LeonOS 44.61%, LeonRT: 1.07%
[14442C10013FE7D600] [3.1.4] [2.003] [system] [warning] PRINT:LeonCss: I: [Timesync] [   4064495] [XLin] startSync:130     Timesync | Callback not set
Reading from Factory EEPROM contents
Reading VERSION 7 --- ->
[ INFO] [1694096923.123239200]: Device type: OAK-FFC-4P
[DEBUG] [1694096923.124398061]: Socket 1 - OV9282
[DEBUG] [1694096923.124416507]: Socket 0 - IMX378
[DEBUG] [1694096923.124425757]: Socket 2 - OV9282
[ WARN] [1694096923.125191253]: Device has no IR drivers
[DEBUG] [1694096923.125790752]: Param camera_i_enable_imu with value 1
[DEBUG] [1694096923.126018241]: Param camera_i_nn_type with value spatial
[DEBUG] [1694096923.126270618]: Param camera_i_pipeline_type with value rgbd
[ INFO] [1694096923.126288167]: Pipeline type: rgbd
[DEBUG] [1694096923.127266916]: Creating ClassLoader, base = depthai_ros_driver::pipeline_gen::BasePipeline, address = 0x7ffc31e7bf30
[DEBUG] [1694096923.127497086]: Entering determineAvailableClasses()...
[DEBUG] [1694096923.127512791]: Processing xml file /home/pr_admin/dai_ws/src/depthai-ros/depthai_ros_driver/plugins.xml...
[DEBUG] [1694096923.127621969]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::RGB, assuming lookup_name == real class name.
[DEBUG] [1694096923.127657594]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::RGBD, assuming lookup_name == real class name.
[DEBUG] [1694096923.127665277]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::RGBStereo, assuming lookup_name == real class name.
[DEBUG] [1694096923.127672791]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::Stereo, assuming lookup_name == real class name.
[DEBUG] [1694096923.127683827]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::Depth, assuming lookup_name == real class name.
[DEBUG] [1694096923.127696636]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::CamArray, assuming lookup_name == real class name.
[DEBUG] [1694096923.127714473]: Exiting determineAvailableClasses()...
[DEBUG] [1694096923.127740936]: Finished constructring ClassLoader, base = depthai_ros_driver::pipeline_gen::BasePipeline, address = 0x7ffc31e7bf30
[DEBUG] [1694096923.127751874]: Attempting to create managed instance for class depthai_ros_driver::pipeline_gen::RGBD.
[DEBUG] [1694096923.127796114]: Class depthai_ros_driver::pipeline_gen::RGBD maps to library lib/libdepthai_ros_driver in classes_available_.
[DEBUG] [1694096923.127911784]: Iterating through all possible paths where lib/libdepthai_ros_driver could be located...
[DEBUG] [1694096923.127925215]: Checking path /home/pr_admin/dai_ws/devel_isolated/pr_rtabmap/lib/lib/libdepthai_ros_driver.so 
[DEBUG] [1694096923.127939136]: Checking path /home/pr_admin/dai_ws/devel_isolated/pr_rtabmap/lib//libdepthai_ros_driver.so 
[DEBUG] [1694096923.127948816]: Checking path /home/pr_admin/dai_ws/devel_isolated/pr_depthai_ros/lib/lib/libdepthai_ros_driver.so 
[DEBUG] [1694096923.127961505]: Checking path /home/pr_admin/dai_ws/devel_isolated/pr_depthai_ros/lib//libdepthai_ros_driver.so 
[DEBUG] [1694096923.127971715]: Checking path /home/pr_admin/dai_ws/devel_isolated/depthai_ros_driver/lib/lib/libdepthai_ros_driver.so 
[DEBUG] [1694096923.127983763]: Checking path /home/pr_admin/dai_ws/devel_isolated/depthai_ros_driver/lib//libdepthai_ros_driver.so 
[DEBUG] [1694096923.127998486]: Library lib/libdepthai_ros_driver found at explicit path /home/pr_admin/dai_ws/devel_isolated/depthai_ros_driver/lib//libdepthai_ros_driver.so.
[DEBUG] [1694096923.128025781]: depthai_ros_driver::pipeline_gen::RGBD maps to real class type depthai_ros_driver::pipeline_gen::RGBD
[DEBUG] [1694096923.128147636]: boost::shared_ptr to object of real type depthai_ros_driver::pipeline_gen::RGBD created.
[DEBUG] [1694096923.128224522]: Creating node rgb base
[DEBUG] [1694096923.128565926]: Param rgb_i_max_q_size with value 30
[DEBUG] [1694096923.128796868]: Param rgb_i_low_bandwidth with value 0
[DEBUG] [1694096923.129016943]: Param rgb_i_low_bandwidth_quality with value 50
[DEBUG] [1694096923.129237051]: Param rgb_i_calibration_file with value 
[DEBUG] [1694096923.129451838]: Param rgb_i_simulate_from_topic with value 0
[DEBUG] [1694096923.129675749]: Param rgb_i_simulated_topic_name with value 
[DEBUG] [1694096923.130020563]: Param rgb_i_disable_node with value 0
[DEBUG] [1694096923.130294981]: Param rgb_i_get_base_device_timestamp with value 0
[DEBUG] [1694096923.130547417]: Param rgb_i_board_socket_id with value 0
[DEBUG] [1694096923.130796961]: Param rgb_i_update_ros_base_time_on_ros_msg with value 0
[DEBUG] [1694096923.131123230]: Param rgb_i_enable_feature_tracker with value 0
[DEBUG] [1694096923.131515072]: Param rgb_i_enable_lazy_publisher with value 1
[DEBUG] [1694096923.131747054]: Param rgb_i_add_exposure_offset with value 0
[DEBUG] [1694096923.131972578]: Param rgb_i_exposure_offset with value 0
[DEBUG] [1694096923.132301671]: Param rgb_i_simulate_from_topic with value 0
[DEBUG] [1694096923.132424521]: Param rgb_i_disable_node with value 0
[DEBUG] [1694096923.132543401]: Param rgb_i_disable_node with value 0
[DEBUG] [1694096923.133588420]: Node rgb has sensor IMX378
[DEBUG] [1694096923.134166905]: Creating node rgb
[DEBUG] [1694096923.134569922]: Param rgb_i_max_q_size with value 30
[DEBUG] [1694096923.134795581]: Param rgb_i_low_bandwidth with value 0
[DEBUG] [1694096923.135023792]: Param rgb_i_low_bandwidth_quality with value 50
[DEBUG] [1694096923.135245163]: Param rgb_i_calibration_file with value 
[DEBUG] [1694096923.135464518]: Param rgb_i_simulate_from_topic with value 0
[DEBUG] [1694096923.135683640]: Param rgb_i_simulated_topic_name with value 
[DEBUG] [1694096923.135909720]: Param rgb_i_disable_node with value 0
[DEBUG] [1694096923.136128048]: Param rgb_i_get_base_device_timestamp with value 0
[DEBUG] [1694096923.136343139]: Param rgb_i_board_socket_id with value 0
[DEBUG] [1694096923.136560599]: Param rgb_i_update_ros_base_time_on_ros_msg with value 0
[DEBUG] [1694096923.136778712]: Param rgb_i_enable_feature_tracker with value 0
[DEBUG] [1694096923.136994917]: Param rgb_i_enable_lazy_publisher with value 1
[DEBUG] [1694096923.137210225]: Param rgb_i_add_exposure_offset with value 0
[DEBUG] [1694096923.137430121]: Param rgb_i_exposure_offset with value 0
[DEBUG] [1694096923.137754420]: Param rgb_i_publish_topic with value 1
[DEBUG] [1694096923.137769594]: Param rgb_i_board_socket_id with value 0
[DEBUG] [1694096923.138225837]: Param rgb_i_output_isp with value 1
[DEBUG] [1694096923.138452623]: Param rgb_i_enable_preview with value 0
[DEBUG] [1694096923.138694268]: Param rgb_i_fps with value 30
[DEBUG] [1694096923.138913240]: Param rgb_i_preview_size with value 300
[DEBUG] [1694096923.139145141]: Param rgb_i_preview_width with value 300
[DEBUG] [1694096923.139367750]: Param rgb_i_preview_height with value 300
[DEBUG] [1694096923.139588524]: Param rgb_i_resolution with value 1080p
[DEBUG] [1694096923.139819473]: Param rgb_i_interleaved with value 0
[DEBUG] [1694096923.140038703]: Param rgb_i_set_isp_scale with value 1
[DEBUG] [1694096923.140252399]: Param rgb_i_isp_num with value 2
[DEBUG] [1694096923.140467611]: Param rgb_i_isp_den with value 3
[DEBUG] [1694096923.140681510]: Param rgb_i_height with value 720
[DEBUG] [1694096923.140894764]: Param rgb_i_width with value 1280
[DEBUG] [1694096923.141109861]: Param rgb_i_keep_preview_aspect_ratio with value 1
[DEBUG] [1694096923.141328020]: Param rgb_r_iso with value 800
[DEBUG] [1694096923.141542794]: Param rgb_r_exposure with value 1000
[DEBUG] [1694096923.141758977]: Param rgb_r_whitebalance with value 3300
[DEBUG] [1694096923.141973042]: Param rgb_r_focus with value 1
[DEBUG] [1694096923.142191223]: Param rgb_r_set_man_focus with value 0
[DEBUG] [1694096923.142405027]: Param rgb_r_set_man_exposure with value 0
[DEBUG] [1694096923.142619976]: Param rgb_r_set_man_whitebalance with value 0
[DEBUG] [1694096923.142833098]: Param rgb_i_fsync_continuous with value 0
[DEBUG] [1694096923.143052580]: Param rgb_i_fsync_trigger with value 0
[DEBUG] [1694096923.143267020]: Param rgb_i_set_isp3a_fps with value 0
[DEBUG] [1694096923.143492001]: Param rgb_i_sensor_img_orientation with value NORMAL
[DEBUG] [1694096923.143617922]: Param rgb_i_publish_topic with value 1
[DEBUG] [1694096923.143798193]: Param rgb_i_low_bandwidth with value 0
[DEBUG] [1694096923.143914196]: Param rgb_i_output_isp with value 1
[DEBUG] [1694096923.144045892]: Param rgb_i_enable_preview with value 0
[DEBUG] [1694096923.144115477]: Node rgb created
[DEBUG] [1694096923.144272860]: Param rgb_i_enable_feature_tracker with value 0
[DEBUG] [1694096923.144280288]: Base node rgb created
[DEBUG] [1694096923.144756146]: Creating node stereo
[DEBUG] [1694096923.145377283]: Param stereo_i_left_socket_id with value 1
[DEBUG] [1694096923.145603447]: Param stereo_i_right_socket_id with value 2
[DEBUG] [1694096923.148057503]: Creating node CAMB-2L base
[DEBUG] [1694096923.148414194]: Destroying ClassLoader, base = depthai_ros_driver::pipeline_gen::BasePipeline, address = 0x7ffc31e7bf30
[ERROR] [1694096923.148509605]: Character [-] at element [4] is not valid in Graph Resource Name [CAMB-2L_i_max_q_size].  Valid characters are a-z, A-Z, 0-9, / and _.
[14442C10013FE7D600] [3.1.4] [1694096923.148] [host] [debug] Device about to be closed...
[2023-09-07 16:28:43.309] [depthai] [debug] XLinkResetRemote of linkId: (0)
[14442C10013FE7D600] [3.1.4] [1694096923.309] [host] [debug] Timesync thread exception caught: Couldn't read data from stream: '__timesync' (X_LINK_ERROR)
[14442C10013FE7D600] [3.1.4] [1694096923.309] [host] [debug] Log thread exception caught: Couldn't read data from stream: '__log' (X_LINK_ERROR)
[14442C10013FE7D600] [3.1.4] [1694096924.604] [host] [debug] Device closed, 1455
[FATAL] [1694096925.719805720]: Failed to load nodelet '/oak` of type `depthai_ros_driver/Camera` to manager `oak_nodelet_manager'
[oak_nodelet_manager-3] process has died [pid 27658, exit code -11, cmd /opt/ros/noetic/lib/nodelet/nodelet manager /nodelet_manager/load_nodelet:=oak/nodelet_manager/load_nodelet /nodelet_manager/unload_nodelet:=oak/nodelet_manager/unload_nodelet /nodelet_manager/list:=oak/nodelet_manager/list __name:=oak_nodelet_manager __log:=/home/pr_admin/.ros/log/cae1d2ce-4d83-11ee-bc82-53e0d77ead1b/oak_nodelet_manager-3.log].
log file: /home/pr_admin/.ros/log/cae1d2ce-4d83-11ee-bc82-53e0d77ead1b/oak_nodelet_manager-3*.log
================================================================================REQUIRED process [oak-4] has died!
```

**Comment by Serafadam** [comment]
Thanks for the information, could you test the fix available [here](https://github.com/luxonis/depthai-ros/pull/398)?

**Comment by ciniminis1** [comment]
@Serafadam Unfortunately, the error still persists in `rgbd` mode.

**Comment by Serafadam** [comment]
Ok, thanks for the info, could you test out this PR? https://github.com/luxonis/depthai-ros/pull/401

**Comment by ciniminis1** [comment]
@Serafadam unfortunately, I still get the same result.

**Comment by Serafadam** [comment]
Hi @martinlucan, could you test that branch and output logs with the latest commits?

**Comment by ciniminis1** [comment]
@Serafadam the same behaviour after pulling the last commit. The error is present only while using OAK-FFC board, it works properly with OAK-Pro and OAK-Pro-W. Please see the log:

```

SUMMARY
========

PARAMETERS
 * /oak/camera_i_base_frame: oak-d_frame
 * /oak/camera_i_cam_pitch: 0.0
 * /oak/camera_i_cam_pos_x: 0.0
 * /oak/camera_i_cam_pos_y: 0.0
 * /oak/camera_i_cam_pos_z: 0.0
 * /oak/camera_i_cam_roll: 0.0
 * /oak/camera_i_cam_yaw: 0.0
 * /oak/camera_i_enable_imu: True
 * /oak/camera_i_enable_ir: True
 * /oak/camera_i_floodlight_brightness: 0.0
 * /oak/camera_i_imu_from_descr: False
 * /oak/camera_i_ip: 
 * /oak/camera_i_laser_dot_brightness: 800.0
 * /oak/camera_i_mx_id: 
 * /oak/camera_i_nn_type: spatial
 * /oak/camera_i_parent_frame: oak-d-base-frame
 * /oak/camera_i_pipeline_type: rgbd
 * /oak/camera_i_publish_tf_from_calibration: False
 * /oak/camera_i_usb_port_id: 
 * /oak/camera_i_usb_speed: SUPER_PLUS
 * /oak/nn_i_nn_config_path: depthai_ros_drive...
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    oak (nodelet/nodelet)
    oak_nodelet_manager (nodelet/nodelet)
    oak_state_publisher (robot_state_publisher/robot_state_publisher)
    set_log_level (rosservice/rosservice)

auto-starting new master
process[master]: started with pid [8473]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e0850dcc-520a-11ee-8767-492a0077deed
process[rosout-1]: started with pid [8496]
started core service [/rosout]
process[set_log_level-2]: started with pid [8503]
process[oak_state_publisher-3]: started with pid [8505]
process[oak_nodelet_manager-4]: started with pid [8506]
process[oak-5]: started with pid [8507]
[ INFO] [1694591718.091179678]: Loading nodelet /oak of type depthai_ros_driver/Camera to manager oak_nodelet_manager with the following remappings:
[ INFO] [1694591718.094120674]: waitForService: Service [/oak_nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1694591718.107210476]: Initializing nodelet with 12 worker threads.
[ INFO] [1694591718.115114128]: waitForService: Service [/oak_nodelet_manager/load_nodelet] is now available.
[2023-09-13 09:55:18.453] [depthai] [info] DEPTHAI_DEBUG enabled, lowered DEPTHAI_LEVEL to 'debug'
[2023-09-13 09:55:18.453] [depthai] [debug] Library information - version: 2.22.0, commit:  from , build: 2023-06-20 18:09:51 +0000
[2023-09-13 09:55:18.456] [depthai] [debug] Initialize - finished
[ INFO] [1694591718.459514362]: No ip/mxid/usb_id specified, connecting to the next available device.
[2023-09-13 09:55:18.612] [depthai] [debug] Resources - Archive 'depthai-bootloader-fwp-0.0.26.tar.xz' open: 5ms, archive read: 149ms
[2023-09-13 09:55:19.207] [depthai] [debug] Resources - Archive 'depthai-device-fwp-f033fd9c7eb0b3578d12f90302e87759c78cfb36.tar.xz' open: 7ms, archive read: 741ms
[2023-09-13 09:55:19.233] [depthai] [debug] Searching for booted device: DeviceInfo(name=1.3, mxid=14442C10013FE7D600, X_LINK_BOOTLOADER, X_LINK_USB_VSC, X_LINK_MYRIAD_X, X_LINK_SUCCESS), name used as hint only
[2023-09-13 09:55:19.237] [depthai] [debug] Connected bootloader version 0.0.22
[2023-09-13 09:55:19.237] [depthai] [info] New bootloader version available. Device has: 0.0.22, available: 0.0.26
[set_log_level-2] process has finished cleanly
log file: /home/martinlucan/.ros/log/e0850dcc-520a-11ee-8767-492a0077deed/set_log_level-2*.log
[2023-09-13 09:55:19.989] [depthai] [debug] DeviceBootloader about to be closed...
[2023-09-13 09:55:19.990] [depthai] [debug] XLinkResetRemote of linkId: (0)
[2023-09-13 09:55:20.737] [depthai] [debug] DeviceBootloader closed, 748
[2023-09-13 09:55:20.748] [depthai] [debug] Searching for booted device: DeviceInfo(name=1.3, mxid=14442C10013FE7D600, X_LINK_BOOTED, X_LINK_USB_VSC, X_LINK_MYRIAD_X, X_LINK_SUCCESS), name used as hint only
[14442C10013FE7D600] [1.3] [2.020] [system] [warning] PRINT:LeonCss: GPIO boot mode 0x3, interface SPI_MASTER_EFF
Setting aons(0..4) back to boot from flash (offset = 0)
====ENABLE WATCHDOG====1
initial keepalive, countdown: 10
PLL0: 700000 AUX_IO0: 24000 AUX_IO1: 24000 MCFG: 24000 MECFG: 24000
Board init ret 3
DepthAI Firmware - version: f033fd9c7eb0b3578d12f90302e87759c78cfb36
eeprom configuration version: 55AA0007
Reading VERSION 7 --- ->
eeprom configuration load from user area, status: 0
Reading VERSION 7 --- ->
Found a device/board entry matching the eeprom data - Board: OAK-FFC-4P (R7M1E7) Device: OAK-FFC-4P
Board options: 00000000
--> brdInit ...
brdInitAuxDevices: Error: SC = 27: io_initialize expander_cam_gpios_1 [OK]

spi_N25Q_init: Flash JEDEC ID: 20 bb 19
inited hal ---
def: 53 46 45 34 10 06 08 34 10 53 14 45 46 08 06
val: 53 46 45 34 10 06 08 34 10 53 14 45 46 08 06
Opening bus for IR driver: 0
Failed to probe IR driver LM3644
Opening bus for IR driver: 1
Failed to probe IR driver LM3644
Opening bus for IR driver: 2
Failed to probe IR driver LM3644
Opening bus for IR driver: 3
Failed to probe IR driver LM3644
Closing EEPROm!
MyriaX board configuration
pll0 frequency: 700000, ref0 frequency: 24000
Is booted from flash by bootloader: 0
Networking not available...
=== Enumerating on socket: Cam_A / RGB / Center
  >> Registered camera A12N02A (imx378) as /dev/Camera_0
camera socket: 0, name: CAMA-4L
        config - w: 1920, h: 1080, type: COLOR
        config - w: 3840, h: 2160, type: COLOR
        config - w: 4056, h: 3040, type: COLOR
Adding socket 0: cam 2. Sen name: IMX378
=== Enumerating on socket: Cam_B / Left
  >> Registered camera TG161B (ov9282) as /dev/Camera_1
camera socket: 1, name: CAMB-2L
        config - w: 1280, h: 720, type: MONO
        config - w: 1280, h: 720, type: COLOR
        config - w: 1280, h: 800, type: MONO
        config - w: 1280, h: 800, type: COLOR
Adding socket 1: cam 5. Sen name: OV9282
=== Enumerating on socket: Cam_C / Right
  >> Registered camera TG161B (ov9282) as /dev/Camera_2
camera socket: 2, name: CAMC-2L
        config - w: 1280, h: 720, type: MONO
        config - w: 1280, h: 720, type: COLOR
        config - w: 1280, h: 800, type: MONO
        config - w: 1280, h: 800, type: COLOR
Adding socket 2: cam 5. Sen name: OV9282
=== Enumerating on socket: CAM_D
initial keepalive, countdown: 9
initial keepalive, countdown: 8
Found a device/board entry matching the eeprom data - Board: OAK-FFC-4P (R7M1E7) Device: OAK-FFC-4P
Initializing XLink...
UsbPumpVscAppI_Event: 5 VSC2_EVENT_ATTACH
UsbPumpVscAppI_Event: 4 VSC2_EVENT_RESET
UsbPumpVscAppI_Event: 4 VSC2_EVENT_RESET
UsbPumpVscAppI_Event: 0 VSC2_EVENT_INTERFACE_UP
Done!
Usb connection speed: Super - USB 3.0
Temperature: Driver registered.
Temperature: Initialized drive
[ INFO] [1694591722.338285207]: Camera with MXID: 14442C10013FE7D600 and Name: 1.3 connected!
[ INFO] [1694591722.339069681]: USB SPEED: SUPER
[14442C10013FE7D600] [1.3] [2.023] [system] [info] Memory Usage - DDR: 0.12 / 337.18 MiB, CMX: 2.04 / 2.50 MiB, LeonOS Heap: 7.51 / 80.03 MiB, LeonRT Heap: 2.89 / 41.06 MiB
[14442C10013FE7D600] [1.3] [2.023] [system] [info] Temperatures - Average: 29.29C, CSS: 30.80C, MSS 28.37C, UPA: 28.86C, DSS: 29.10C
[14442C10013FE7D600] [1.3] [2.023] [system] [info] Cpu Usage - LeonOS 61.13%, LeonRT: 1.07%
[14442C10013FE7D600] [1.3] [2.030] [system] [warning] PRINT:LeonCss: r.
Temperature: Sensor opened: CSS.
Temperature: Sensor opened: MSS.
Temperature: Sensor opened: UPA.
Temperature: Sensor opened: DSS.
I: [Timesync] [   6284385] [XLin] startSync:130     Timesync | Callback not set
Reading from Factory EEPROM contents
Reading VERSION 7 --- ->
[ INFO] [1694591722.348875542]: Device type: OAK-FFC-4P
[DEBUG] [1694591722.350051758]: Socket 1 - OV9282
[DEBUG] [1694591722.350103781]: Socket 0 - IMX378
[DEBUG] [1694591722.350138267]: Socket 2 - OV9282
[ WARN] [1694591722.351042376]: Device has no IR drivers
[DEBUG] [1694591722.352371716]: Param camera_i_enable_imu with value 1
[DEBUG] [1694591722.352985665]: Param camera_i_nn_type with value spatial
[DEBUG] [1694591722.353580773]: Param camera_i_pipeline_type with value rgbd
[ INFO] [1694591722.353642079]: Pipeline type: rgbd
[DEBUG] [1694591722.354837439]: Creating ClassLoader, base = depthai_ros_driver::pipeline_gen::BasePipeline, address = 0x7ffeb7574790
[DEBUG] [1694591722.355221578]: Entering determineAvailableClasses()...
[DEBUG] [1694591722.355272558]: Processing xml file /home/martinlucan/dai_ws/src/depthai-ros/depthai_ros_driver/plugins.xml...
[DEBUG] [1694591722.355482779]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::RGB, assuming lookup_name == real class name.
[DEBUG] [1694591722.355536643]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::RGBD, assuming lookup_name == real class name.
[DEBUG] [1694591722.355562253]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::RGBStereo, assuming lookup_name == real class name.
[DEBUG] [1694591722.355586335]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::Stereo, assuming lookup_name == real class name.
[DEBUG] [1694591722.355609346]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::Depth, assuming lookup_name == real class name.
[DEBUG] [1694591722.355633251]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::CamArray, assuming lookup_name == real class name.
[DEBUG] [1694591722.355665843]: Exiting determineAvailableClasses()...
[DEBUG] [1694591722.355724692]: Finished constructring ClassLoader, base = depthai_ros_driver::pipeline_gen::BasePipeline, address = 0x7ffeb7574790
[DEBUG] [1694591722.355749465]: Attempting to create managed instance for class depthai_ros_driver::pipeline_gen::RGBD.
[DEBUG] [1694591722.355843556]: Class depthai_ros_driver::pipeline_gen::RGBD maps to library lib/libdepthai_ros_driver in classes_available_.
[DEBUG] [1694591722.356086683]: Iterating through all possible paths where lib/libdepthai_ros_driver could be located...
[DEBUG] [1694591722.356120434]: Checking path /home/martinlucan/dai_ws/devel/lib/lib/libdepthai_ros_driver.so 
[DEBUG] [1694591722.356146046]: Checking path /home/martinlucan/dai_ws/devel/lib//libdepthai_ros_driver.so 
[DEBUG] [1694591722.356168357]: Library lib/libdepthai_ros_driver found at explicit path /home/martinlucan/dai_ws/devel/lib//libdepthai_ros_driver.so.
[DEBUG] [1694591722.356222980]: depthai_ros_driver::pipeline_gen::RGBD maps to real class type depthai_ros_driver::pipeline_gen::RGBD
[DEBUG] [1694591722.356504075]: boost::shared_ptr to object of real type depthai_ros_driver::pipeline_gen::RGBD created.
[DEBUG] [1694591722.356683270]: Creating node rgb base
[DEBUG] [1694591722.357459352]: Param rgb_i_max_q_size with value 30
[DEBUG] [1694591722.358908734]: Param rgb_i_low_bandwidth with value 0
[DEBUG] [1694591722.360215526]: Param rgb_i_low_bandwidth_quality with value 50
[DEBUG] [1694591722.361492784]: Param rgb_i_calibration_file with value 
[DEBUG] [1694591722.362447054]: Param rgb_i_simulate_from_topic with value 0
[DEBUG] [1694591722.363377338]: Param rgb_i_simulated_topic_name with value 
[DEBUG] [1694591722.364317420]: Param rgb_i_disable_node with value 0
[DEBUG] [1694591722.365265862]: Param rgb_i_get_base_device_timestamp with value 0
[DEBUG] [1694591722.366413501]: Param rgb_i_board_socket_id with value 0
[DEBUG] [1694591722.367643403]: Param rgb_i_update_ros_base_time_on_ros_msg with value 0
[DEBUG] [1694591722.368779384]: Param rgb_i_enable_feature_tracker with value 0
[DEBUG] [1694591722.369836236]: Param rgb_i_enable_lazy_publisher with value 1
[DEBUG] [1694591722.371066484]: Param rgb_i_add_exposure_offset with value 0
[DEBUG] [1694591722.372046069]: Param rgb_i_exposure_offset with value 0
[DEBUG] [1694591722.373603997]: Param rgb_i_simulate_from_topic with value 0
[DEBUG] [1694591722.374136064]: Param rgb_i_disable_node with value 0
[DEBUG] [1694591722.374567660]: Param rgb_i_disable_node with value 0
[DEBUG] [1694591722.375769482]: Node rgb has sensor IMX378
[DEBUG] [1694591722.377115795]: Creating node rgb
[DEBUG] [1694591722.378455174]: Param rgb_i_max_q_size with value 30
[DEBUG] [1694591722.379279452]: Param rgb_i_low_bandwidth with value 0
[DEBUG] [1694591722.380039856]: Param rgb_i_low_bandwidth_quality with value 50
[DEBUG] [1694591722.380768145]: Param rgb_i_calibration_file with value 
[DEBUG] [1694591722.381540122]: Param rgb_i_simulate_from_topic with value 0
[DEBUG] [1694591722.382263937]: Param rgb_i_simulated_topic_name with value 
[DEBUG] [1694591722.382980160]: Param rgb_i_disable_node with value 0
[DEBUG] [1694591722.383734304]: Param rgb_i_get_base_device_timestamp with value 0
[DEBUG] [1694591722.384490925]: Param rgb_i_board_socket_id with value 0
[DEBUG] [1694591722.385560249]: Param rgb_i_update_ros_base_time_on_ros_msg with value 0
[DEBUG] [1694591722.386370334]: Param rgb_i_enable_feature_tracker with value 0
[DEBUG] [1694591722.387253527]: Param rgb_i_enable_lazy_publisher with value 1
[DEBUG] [1694591722.388102360]: Param rgb_i_add_exposure_offset with value 0
[DEBUG] [1694591722.388866980]: Param rgb_i_exposure_offset with value 0
[DEBUG] [1694591722.389494871]: Param rgb_i_publish_topic with value 1
[DEBUG] [1694591722.390087621]: Param rgb_i_board_socket_id with value 0
[DEBUG] [1694591722.390994478]: Param rgb_i_output_isp with value 1
[DEBUG] [1694591722.391887376]: Param rgb_i_enable_preview with value 0
[DEBUG] [1694591722.392954775]: Param rgb_i_fps with value 30
[DEBUG] [1694591722.393922885]: Param rgb_i_preview_size with value 300
[DEBUG] [1694591722.394831231]: Param rgb_i_preview_width with value 300
[DEBUG] [1694591722.395679899]: Param rgb_i_preview_height with value 300
[DEBUG] [1694591722.396531866]: Param rgb_i_resolution with value 1080p
[DEBUG] [1694591722.397441065]: Param rgb_i_interleaved with value 0
[DEBUG] [1694591722.398296957]: Param rgb_i_set_isp_scale with value 1
[DEBUG] [1694591722.399138754]: Param rgb_i_isp_num with value 2
[DEBUG] [1694591722.400056288]: Param rgb_i_isp_den with value 3
[DEBUG] [1694591722.401096408]: Param rgb_i_height with value 720
[DEBUG] [1694591722.401978561]: Param rgb_i_width with value 1280
[DEBUG] [1694591722.402939579]: Param rgb_i_keep_preview_aspect_ratio with value 1
[DEBUG] [1694591722.404190665]: Param rgb_r_iso with value 800
[DEBUG] [1694591722.404930941]: Param rgb_r_exposure with value 1000
[DEBUG] [1694591722.405647443]: Param rgb_r_whitebalance with value 3300
[DEBUG] [1694591722.406365917]: Param rgb_r_focus with value 1
[DEBUG] [1694591722.407129884]: Param rgb_r_set_man_focus with value 0
[DEBUG] [1694591722.407885096]: Param rgb_r_set_man_exposure with value 0
[DEBUG] [1694591722.408578157]: Param rgb_r_set_man_whitebalance with value 0
[DEBUG] [1694591722.408977253]: Param rgb_i_fsync_continuous with value 0
[DEBUG] [1694591722.409833908]: Param rgb_i_fsync_trigger with value 0
[DEBUG] [1694591722.410686750]: Param rgb_i_set_isp3a_fps with value 0
[DEBUG] [1694591722.411534862]: Param rgb_i_sensor_img_orientation with value NORMAL
[DEBUG] [1694591722.412413358]: Param rgb_i_publish_topic with value 1
[DEBUG] [1694591722.412998356]: Param rgb_i_low_bandwidth with value 0
[DEBUG] [1694591722.413369275]: Param rgb_i_output_isp with value 1
[DEBUG] [1694591722.413878758]: Param rgb_i_enable_preview with value 0
[DEBUG] [1694591722.414133619]: Node rgb created
[DEBUG] [1694591722.414709363]: Param rgb_i_enable_feature_tracker with value 0
[DEBUG] [1694591722.414734396]: Base node rgb created
[DEBUG] [1694591722.416082612]: Creating node stereo
[DEBUG] [1694591722.417801064]: Param stereo_i_left_socket_id with value 1
[DEBUG] [1694591722.418686324]: Param stereo_i_right_socket_id with value 2
[DEBUG] [1694591722.422547804]: Creating node CAMB-2L base
[DEBUG] [1694591722.423293478]: Destroying ClassLoader, base = depthai_ros_driver::pipeline_gen::BasePipeline, address = 0x7ffeb7574790
[ERROR] [1694591722.423471654]: Character [-] at element [4] is not valid in Graph Resource Name [CAMB-2L_i_max_q_size].  Valid characters are a-z, A-Z, 0-9, / and _.
[14442C10013FE7D600] [1.3] [1694591722.423] [host] [debug] Device about to be closed...
[14442C10013FE7D600] [1.3] [1694591723.081] [host] [debug] Watchdog thread exception caught: Couldn't write data to stream: '__watchdog' (X_LINK_ERROR)
[14442C10013FE7D600] [1.3] [1694591723.283] [host] [debug] Timesync thread exception caught: Couldn't read data from stream: '__timesync' (X_LINK_ERROR)
[14442C10013FE7D600] [1.3] [1694591723.283] [host] [debug] Log thread exception caught: Couldn't read data from stream: '__log' (X_LINK_ERROR)
[2023-09-13 09:55:23.283] [depthai] [debug] XLinkResetRemote of linkId: (0)
[14442C10013FE7D600] [1.3] [1694591723.829] [host] [debug] Device closed, 1405
[FATAL] [1694591725.320346554]: Failed to load nodelet '/oak` of type `depthai_ros_driver/Camera` to manager `oak_nodelet_manager'
[oak_nodelet_manager-4] process has died [pid 8506, exit code -11, cmd /opt/ros/noetic/lib/nodelet/nodelet manager /nodelet_manager/load_nodelet:=oak/nodelet_manager/load_nodelet /nodelet_manager/unload_nodelet:=oak/nodelet_manager/unload_nodelet /nodelet_manager/list:=oak/nodelet_manager/list __name:=oak_nodelet_manager __log:=/home/martinlucan/.ros/log/e0850dcc-520a-11ee-8767-492a0077deed/oak_nodelet_manager-4.log].
```

**Comment by Serafadam** [comment]
Could you retry on the latest noetic branch? [This line](https://github.com/luxonis/depthai-ros/blob/1123a3bcb22ca51dc6c7823caf381d7f4e67011a/depthai_ros_driver/src/dai_nodes/stereo.cpp#L44) should also be printed before "Creating node base"

**Comment by ciniminis1** [comment]
@Serafadam sure, I am on the latest noetic branch. Check out the log output, the error seems to be pointing to invalid naming characters.

```

SUMMARY
========

PARAMETERS
 * /oak/camera_i_base_frame: oak-d_frame
 * /oak/camera_i_cam_pitch: 0.0
 * /oak/camera_i_cam_pos_x: 0.0
 * /oak/camera_i_cam_pos_y: 0.0
 * /oak/camera_i_cam_pos_z: 0.0
 * /oak/camera_i_cam_roll: 0.0
 * /oak/camera_i_cam_yaw: 0.0
 * /oak/camera_i_enable_imu: True
 * /oak/camera_i_enable_ir: True
 * /oak/camera_i_floodlight_brightness: 0.0
 * /oak/camera_i_imu_from_descr: False
 * /oak/camera_i_ip: 
 * /oak/camera_i_laser_dot_brightness: 800.0
 * /oak/camera_i_mx_id: 
 * /oak/camera_i_nn_type: spatial
 * /oak/camera_i_parent_frame: oak-d-base-frame
 * /oak/camera_i_pipeline_type: rgbd
 * /oak/camera_i_publish_tf_from_calibration: False
 * /oak/camera_i_usb_port_id: 
 * /oak/camera_i_usb_speed: SUPER_PLUS
 * /oak/nn_i_nn_config_path: depthai_ros_drive...
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    oak (nodelet/nodelet)
    oak_nodelet_manager (nodelet/nodelet)
    oak_state_publisher (robot_state_publisher/robot_state_publisher)
    set_log_level (rosservice/rosservice)

auto-starting new master
process[master]: started with pid [7051]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f01c7e30-5234-11ee-8933-ad3ae5157825
process[rosout-1]: started with pid [7073]
started core service [/rosout]
process[set_log_level-2]: started with pid [7080]
process[oak_state_publisher-3]: started with pid [7081]
process[oak_nodelet_manager-4]: started with pid [7082]
process[oak-5]: started with pid [7083]
[ INFO] [1694609782.395209233]: Loading nodelet /oak of type depthai_ros_driver/Camera to manager oak_nodelet_manager with the following remappings:
[ INFO] [1694609782.397247351]: waitForService: Service [/oak_nodelet_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1694609782.408298799]: Initializing nodelet with 12 worker threads.
[ INFO] [1694609782.417920262]: waitForService: Service [/oak_nodelet_manager/load_nodelet] is now available.
[2023-09-13 14:56:22.609] [depthai] [info] DEPTHAI_DEBUG enabled, lowered DEPTHAI_LEVEL to 'debug'
[2023-09-13 14:56:22.609] [depthai] [debug] Library information - version: 2.22.0, commit:  from , build: 2023-06-20 18:09:51 +0000
[2023-09-13 14:56:22.610] [depthai] [debug] Initialize - finished
[ INFO] [1694609782.611881727]: No ip/mxid/usb_id specified, connecting to the next available device.
[2023-09-13 14:56:22.742] [depthai] [debug] Resources - Archive 'depthai-bootloader-fwp-0.0.26.tar.xz' open: 3ms, archive read: 126ms
[2023-09-13 14:56:23.100] [depthai] [debug] Resources - Archive 'depthai-device-fwp-f033fd9c7eb0b3578d12f90302e87759c78cfb36.tar.xz' open: 3ms, archive read: 487ms
[2023-09-13 14:56:23.203] [depthai] [debug] Searching for booted device: DeviceInfo(name=1.3.1, mxid=14442C10013FE7D600, X_LINK_BOOTLOADER, X_LINK_USB_VSC, X_LINK_MYRIAD_X, X_LINK_SUCCESS), name used as hint only
[2023-09-13 14:56:23.207] [depthai] [debug] Connected bootloader version 0.0.22
[2023-09-13 14:56:23.207] [depthai] [info] New bootloader version available. Device has: 0.0.22, available: 0.0.26
[set_log_level-2] process has finished cleanly
log file: /home/martinlucan/.ros/log/f01c7e30-5234-11ee-8933-ad3ae5157825/set_log_level-2*.log
[2023-09-13 14:56:23.973] [depthai] [debug] DeviceBootloader about to be closed...
[2023-09-13 14:56:23.974] [depthai] [debug] XLinkResetRemote of linkId: (0)
[2023-09-13 14:56:24.708] [depthai] [debug] DeviceBootloader closed, 734
[2023-09-13 14:56:24.715] [depthai] [debug] Searching for booted device: DeviceInfo(name=1.3.1, mxid=14442C10013FE7D600, X_LINK_BOOTED, X_LINK_USB_VSC, X_LINK_MYRIAD_X, X_LINK_SUCCESS), name used as hint only
[14442C10013FE7D600] [1.3.1] [1.996] [system] [warning] PRINT:LeonCss: GPIO boot mode 0x3, interface SPI_MASTER_EFF
Setting aons(0..4) back to boot from flash (offset = 0)
====ENABLE WATCHDOG====1
initial keepalive, countdown: 10
PLL0: 700000 AUX_IO0: 24000 AUX_IO1: 24000 MCFG: 24000 MECFG: 24000
Board init ret 3
DepthAI Firmware - version: f033fd9c7eb0b3578d12f90302e87759c78cfb36
eeprom configuration version: 55AA0007
Reading VERSION 7 --- ->
eeprom configuration load from user area, status: 0
Reading VERSION 7 --- ->
Found a device/board entry matching the eeprom data - Board: OAK-FFC-4P (R7M1E7) Device: OAK-FFC-4P
Board options: 00000000
--> brdInit ...
brdInitAuxDevices: Error: SC = 27: io_initialize expander_cam_gpios_1 [OK]

spi_N25Q_init: Flash JEDEC ID: 20 bb 19
inited hal ---
def: 53 46 45 34 10 06 08 34 10 53 14 45 46 08 06
val: 53 46 45 34 10 06 08 34 10 53 14 45 46 08 06
Opening bus for IR driver: 0
Failed to probe IR driver LM3644
Opening bus for IR driver: 1
Failed to probe IR driver LM3644
Opening bus for IR driver: 2
Failed to probe IR driver LM3644
Opening bus for IR driver: 3
Failed to probe IR driver LM3644
Closing EEPROm!
MyriaX board configuration
pll0 frequency: 700000, ref0 frequency: 24000
Is booted from flash by bootloader: 0
Networking not available...
=== Enumerating on socket: Cam_A / RGB / Center
  >> Registered camera A12N02A (imx378) as /dev/Camera_0
camera socket: 0, name: CAMA-4L
        config - w: 1920, h: 1080, type: COLOR
        config - w: 3840, h: 2160, type: COLOR
        config - w: 4056, h: 3040, type: COLOR
Adding socket 0: cam 2. Sen name: IMX378
=== Enumerating on socket: Cam_B / Left
  >> Registered camera TG161B (ov9282) as /dev/Camera_1
camera socket: 1, name: CAMB-2L
        config - w: 1280, h: 720, type: MONO
        config - w: 1280, h: 720, type: COLOR
        config - w: 1280, h: 800, type: MONO
        config - w: 1280, h: 800, type: COLOR
Adding socket 1: cam 5. Sen name: OV9282
=== Enumerating on socket: Cam_C / Right
  >> Registered camera TG161B (ov9282) as /dev/Camera_2
camera socket: 2, name: CAMC-2L
        config - w: 1280, h: 720, type: MONO
        config - w: 1280, h: 720, type: COLOR
        config - w: 1280, h: 800, type: MONO
        config - w: 1280, h: 800, type: COLOR
Adding socket 2: cam 5. Sen name: OV9282
=== Enumerating on socket: CAM_D
initial keepalive, countdown: 9
initial keepalive, countdown: 8
Found a device/board entry matching the eeprom data - Board: OAK-FFC-4P (R7M1E7) Device: OAK-FFC-4P
Initializing XLink...
UsbPumpVscAppI_Event: 5 VSC2_EVENT_ATTACH
UsbPumpVscAppI_Event: 4 VSC2_EVENT_RESET
UsbPumpVscAppI_Event: 4 VSC2_EVENT_RESET
UsbPumpVscAppI_Event: 0 VSC2_EVENT_INTERFACE_UP
Done!
Usb connection speed: Super - USB 3.0
Temperature: Driver registered.
Temperature: Initialized driver.
Temperature: Sensor opened: CSS.
Temperature: Sensor opened: MSS.
Temperature: Sensor opened: UPA.
Temperature: Sensor opened: DSS.
[ INFO] [1694609786.299218288]: Camera with MXID: 14442C10013FE7D600 and Name: 1.3.1 connected!
[ INFO] [1694609786.299958505]: USB SPEED: SUPER
[14442C10013FE7D600] [1.3.1] [2.000] [system] [info] Memory Usage - DDR: 0.12 / 337.18 MiB, CMX: 2.04 / 2.50 MiB, LeonOS Heap: 7.51 / 80.03 MiB, LeonRT Heap: 2.89 / 41.06 MiB
[14442C10013FE7D600] [1.3.1] [2.000] [system] [info] Temperatures - Average: 36.06C, CSS: 37.01C, MSS 35.11C, UPA: 36.06C, DSS: 36.06C
[14442C10013FE7D600] [1.3.1] [2.000] [system] [info] Cpu Usage - LeonOS 37.83%, LeonRT: 1.07%
[14442C10013FE7D600] [1.3.1] [2.006] [system] [warning] PRINT:LeonCss: I: [Timesync] [   3519457] [XLin] startSync:130     Timesync | Callback not set
Reading from Factory EEPROM contents
Reading VERSION 7 --- ->
[ INFO] [1694609786.309283068]: Device type: OAK-FFC-4P
[DEBUG] [1694609786.310284731]: Socket 1 - OV9282
[DEBUG] [1694609786.310305662]: Socket 0 - IMX378
[DEBUG] [1694609786.310314051]: Socket 2 - OV9282
[ WARN] [1694609786.311031388]: Device has no IR drivers
[DEBUG] [1694609786.311697555]: Param camera_i_enable_imu with value 1
[DEBUG] [1694609786.311964195]: Param camera_i_nn_type with value spatial
[DEBUG] [1694609786.312201711]: Param camera_i_pipeline_type with value rgbd
[ INFO] [1694609786.312228492]: Pipeline type: rgbd
[DEBUG] [1694609786.313419476]: Creating ClassLoader, base = depthai_ros_driver::pipeline_gen::BasePipeline, address = 0x7ffc56629280
[DEBUG] [1694609786.313655571]: Entering determineAvailableClasses()...
[DEBUG] [1694609786.313684476]: Processing xml file /home/martinlucan/dai_ws/src/depthai-ros/depthai_ros_driver/plugins.xml...
[DEBUG] [1694609786.313825335]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::RGB, assuming lookup_name == real class name.
[DEBUG] [1694609786.313863404]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::RGBD, assuming lookup_name == real class name.
[DEBUG] [1694609786.313884955]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::RGBStereo, assuming lookup_name == real class name.
[DEBUG] [1694609786.313909365]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::Stereo, assuming lookup_name == real class name.
[DEBUG] [1694609786.313930532]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::Depth, assuming lookup_name == real class name.
[DEBUG] [1694609786.313952467]: XML file has no lookup name (i.e. magic name) for class depthai_ros_driver::pipeline_gen::CamArray, assuming lookup_name == real class name.
[DEBUG] [1694609786.313980288]: Exiting determineAvailableClasses()...
[DEBUG] [1694609786.314023061]: Finished constructring ClassLoader, base = depthai_ros_driver::pipeline_gen::BasePipeline, address = 0x7ffc56629280
[DEBUG] [1694609786.314044363]: Attempting to create managed instance for class depthai_ros_driver::pipeline_gen::RGBD.
[DEBUG] [1694609786.314109441]: Class depthai_ros_driver::pipeline_gen::RGBD maps to library lib/libdepthai_ros_driver in classes_available_.
[DEBUG] [1694609786.314284279]: Iterating through all possible paths where lib/libdepthai_ros_driver could be located...
[DEBUG] [1694609786.314306126]: Checking path /home/martinlucan/dai_ws/devel/lib/lib/libdepthai_ros_driver.so 
[DEBUG] [1694609786.314322433]: Checking path /home/martinlucan/dai_ws/devel/lib//libdepthai_ros_driver.so 
[DEBUG] [1694609786.314343760]: Library lib/libdepthai_ros_driver found at explicit path /home/martinlucan/dai_ws/devel/lib//libdepthai_ros_driver.so.
[DEBUG] [1694609786.314387698]: depthai_ros_driver::pipeline_gen::RGBD maps to real class type depthai_ros_driver::pipeline_gen::RGBD
[DEBUG] [1694609786.314572550]: boost::shared_ptr to object of real type depthai_ros_driver::pipeline_gen::RGBD created.
[DEBUG] [1694609786.314678449]: Creating node rgb base
[DEBUG] [1694609786.315028399]: Param rgb_i_max_q_size with value 30
[DEBUG] [1694609786.315740150]: Param rgb_i_low_bandwidth with value 0
[DEBUG] [1694609786.316279629]: Param rgb_i_low_bandwidth_quality with value 50
[DEBUG] [1694609786.316921192]: Param rgb_i_calibration_file with value 
[DEBUG] [1694609786.317441624]: Param rgb_i_simulate_from_topic with value 0
[DEBUG] [1694609786.317956004]: Param rgb_i_simulated_topic_name with value 
[DEBUG] [1694609786.318482807]: Param rgb_i_disable_node with value 0
[DEBUG] [1694609786.318993681]: Param rgb_i_get_base_device_timestamp with value 0
[DEBUG] [1694609786.319506672]: Param rgb_i_board_socket_id with value 0
[DEBUG] [1694609786.320020863]: Param rgb_i_update_ros_base_time_on_ros_msg with value 0
[DEBUG] [1694609786.320538132]: Param rgb_i_enable_feature_tracker with value 0
[DEBUG] [1694609786.321044463]: Param rgb_i_enable_lazy_publisher with value 1
[DEBUG] [1694609786.321543205]: Param rgb_i_add_exposure_offset with value 0
[DEBUG] [1694609786.322038164]: Param rgb_i_exposure_offset with value 0
[DEBUG] [1694609786.322910639]: Param rgb_i_simulate_from_topic with value 0
[DEBUG] [1694609786.323159323]: Param rgb_i_disable_node with value 0
[DEBUG] [1694609786.323400690]: Param rgb_i_disable_node with value 0
[DEBUG] [1694609786.324466514]: Node rgb has sensor IMX378
[DEBUG] [1694609786.325318445]: Creating node rgb
[DEBUG] [1694609786.325959563]: Param rgb_i_max_q_size with value 30
[DEBUG] [1694609786.326397361]: Param rgb_i_low_bandwidth with value 0
[DEBUG] [1694609786.326813738]: Param rgb_i_low_bandwidth_quality with value 50
[DEBUG] [1694609786.327227196]: Param rgb_i_calibration_file with value 
[DEBUG] [1694609786.327636969]: Param rgb_i_simulate_from_topic with value 0
[DEBUG] [1694609786.328047185]: Param rgb_i_simulated_topic_name with value 
[DEBUG] [1694609786.328452079]: Param rgb_i_disable_node with value 0
[DEBUG] [1694609786.328858107]: Param rgb_i_get_base_device_timestamp with value 0
[DEBUG] [1694609786.329269368]: Param rgb_i_board_socket_id with value 0
[DEBUG] [1694609786.329680321]: Param rgb_i_update_ros_base_time_on_ros_msg with value 0
[DEBUG] [1694609786.330087648]: Param rgb_i_enable_feature_tracker with value 0
[DEBUG] [1694609786.330508224]: Param rgb_i_enable_lazy_publisher with value 1
[DEBUG] [1694609786.330920353]: Param rgb_i_add_exposure_offset with value 0
[DEBUG] [1694609786.331331639]: Param rgb_i_exposure_offset with value 0
[DEBUG] [1694609786.331688176]: Param rgb_i_publish_topic with value 1
[DEBUG] [1694609786.332003050]: Param rgb_i_board_socket_id with value 0
[DEBUG] [1694609786.332504385]: Param rgb_i_output_isp with value 1
[DEBUG] [1694609786.332999502]: Param rgb_i_enable_preview with value 0
[DEBUG] [1694609786.333518177]: Param rgb_i_fps with value 30
[DEBUG] [1694609786.334023106]: Param rgb_i_preview_size with value 300
[DEBUG] [1694609786.334533081]: Param rgb_i_preview_width with value 300
[DEBUG] [1694609786.335028951]: Param rgb_i_preview_height with value 300
[DEBUG] [1694609786.335530606]: Param rgb_i_resolution with value 1080p
[DEBUG] [1694609786.336043923]: Param rgb_i_interleaved with value 0
[DEBUG] [1694609786.336539946]: Param rgb_i_set_isp_scale with value 1
[DEBUG] [1694609786.337032625]: Param rgb_i_isp_num with value 2
[DEBUG] [1694609786.337544070]: Param rgb_i_isp_den with value 3
[DEBUG] [1694609786.338029879]: Param rgb_i_height with value 720
[DEBUG] [1694609786.338526737]: Param rgb_i_width with value 1280
[DEBUG] [1694609786.339019461]: Param rgb_i_keep_preview_aspect_ratio with value 1
[DEBUG] [1694609786.339685907]: Param rgb_r_iso with value 800
[DEBUG] [1694609786.340089824]: Param rgb_r_exposure with value 1000
[DEBUG] [1694609786.340498467]: Param rgb_r_whitebalance with value 3300
[DEBUG] [1694609786.340890233]: Param rgb_r_focus with value 1
[DEBUG] [1694609786.341298078]: Param rgb_r_set_man_focus with value 0
[DEBUG] [1694609786.341708616]: Param rgb_r_set_man_exposure with value 0
[DEBUG] [1694609786.342113465]: Param rgb_r_set_man_whitebalance with value 0
[DEBUG] [1694609786.342356002]: Param rgb_i_fsync_continuous with value 0
[DEBUG] [1694609786.342833758]: Param rgb_i_fsync_trigger with value 0
[DEBUG] [1694609786.343317408]: Param rgb_i_set_isp3a_fps with value 0
[DEBUG] [1694609786.343795120]: Param rgb_i_sensor_img_orientation with value NORMAL
[DEBUG] [1694609786.344281032]: Param rgb_i_publish_topic with value 1
[DEBUG] [1694609786.344566564]: Param rgb_i_low_bandwidth with value 0
[DEBUG] [1694609786.344777921]: Param rgb_i_output_isp with value 1
[DEBUG] [1694609786.345004524]: Param rgb_i_enable_preview with value 0
[DEBUG] [1694609786.345088641]: Node rgb created
[DEBUG] [1694609786.345344285]: Param rgb_i_enable_feature_tracker with value 0
[DEBUG] [1694609786.345361492]: Base node rgb created
[DEBUG] [1694609786.345949096]: Creating node stereo
[DEBUG] [1694609786.346861570]: Param stereo_i_left_socket_id with value 1
[DEBUG] [1694609786.347327217]: Param stereo_i_right_socket_id with value 2
[DEBUG] [1694609786.349973913]: Creating node CAMB-2L base
[DEBUG] [1694609786.350413264]: Destroying ClassLoader, base = depthai_ros_driver::pipeline_gen::BasePipeline, address = 0x7ffc56629280
[ERROR] [1694609786.350532359]: Character [-] at element [4] is not valid in Graph Resource Name [CAMB-2L_i_max_q_size].  Valid characters are a-z, A-Z, 0-9, / and _.
[14442C10013FE7D600] [1.3.1] [1694609786.350] [host] [debug] Device about to be closed...
[14442C10013FE7D600] [1.3.1] [1694609787.043] [host] [debug] Watchdog thread exception caught: Couldn't write data to stream: '__watchdog' (X_LINK_ERROR)
[14442C10013FE7D600] [1.3.1] [1694609787.181] [host] [debug] Log thread exception caught: Couldn't read data from stream: '__log' (X_LINK_ERROR)
[2023-09-13 14:56:27.181] [depthai] [debug] XLinkResetRemote of linkId: (0)
[14442C10013FE7D600] [1.3.1] [1694609787.181] [host] [debug] Timesync thread exception caught: Couldn't read data from stream: '__timesync' (X_LINK_ERROR)
[14442C10013FE7D600] [1.3.1] [1694609787.791] [host] [debug] Device closed, 1440
[FATAL] [1694609788.974366775]: Failed to load nodelet '/oak` of type `depthai_ros_driver/Camera` to manager `oak_nodelet_manager'
[oak_nodelet_manager-4] process has died [pid 7082, exit code -11, 
```

**Comment by Serafadam** [comment]
@martinlucan, latest noetic version should also print out this line 
`"Creating stereo node with left sensor %s and right sensor %s",`
before 
`Creating node CAMB-2L base`, could you check if you correctly sourced the workspace after building?

**Comment by ciniminis1** [comment]
@Serafadam Thank you, it is working properly after the complete rebuild of the package

**Comment by Serafadam** [comment]
Closing the issue since it's resolved.
